### ISSUE TITLE
Network related crash

### ISSUE THREAD

**Issue by dowski** [dowski/scoreboard#11]
```
Aug 07 12:51:26 scoreboard2 scoreboard[342]: rescheduling GameTracker; error fetching due to
Aug 07 12:51:46 scoreboard2 scoreboard[342]: Traceback (most recent call last):
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/urllib3-1.25.10-py3.7.egg/urllib3/connection.py", line 160, in _new_conn
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     (self._dns_host, self.port), self.timeout, **extra_kw
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/urllib3-1.25.10-py3.7.egg/urllib3/util/connection.py", line 61, in create_c
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Aug 07 12:51:46 scoreboard2 scoreboard[342]: socket.gaierror: [Errno -3] Temporary failure in name resolution
Aug 07 12:51:46 scoreboard2 scoreboard[342]: During handling of the above exception, another exception occurred:
Aug 07 12:51:46 scoreboard2 scoreboard[342]: Traceback (most recent call last):
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/scoreboard/scoreboard/mlb.py", line 75, in get_game_detail
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     'fields': "gameData,teams,teamName,status,detailedState,liveData,linescore,home,away,runs,hits,errors,offense,outs,balls,strike
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/MLB_StatsAPI-1.0.0-py3.7.egg/statsapi/__init__.py", line 1642, in get
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     r = requests.get(url)
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/requests-2.24.0-py3.7.egg/requests/api.py", line 76, in get
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     return request('get', url, params=params, **kwargs)
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/requests-2.24.0-py3.7.egg/requests/api.py", line 61, in request
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     return session.request(method=method, url=url, **kwargs)
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/requests-2.24.0-py3.7.egg/requests/sessions.py", line 530, in request
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     resp = self.send(prep, **send_kwargs)
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/requests-2.24.0-py3.7.egg/requests/sessions.py", line 643, in send
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     r = adapter.send(request, **kwargs)
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/requests-2.24.0-py3.7.egg/requests/adapters.py", line 449, in send
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     timeout=timeout
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/urllib3-1.25.10-py3.7.egg/urllib3/connectionpool.py", line 677, in urlopen
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     chunked=chunked,
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/urllib3-1.25.10-py3.7.egg/urllib3/connectionpool.py", line 381, in _make_re
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     self._validate_conn(conn)
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/urllib3-1.25.10-py3.7.egg/urllib3/connectionpool.py", line 978, in _validat
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     conn.connect()
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/urllib3-1.25.10-py3.7.egg/urllib3/connection.py", line 309, in connect
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     conn = self._new_conn()
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/urllib3-1.25.10-py3.7.egg/urllib3/connection.py", line 160, in _new_conn
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     (self._dns_host, self.port), self.timeout, **extra_kw
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/scoreboard/scoreboard/mlb.py", line 106, in handle_alarm
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     raise _Timeout()
Aug 07 12:51:46 scoreboard2 scoreboard[342]: scoreboard.mlb._Timeout
Aug 07 12:51:46 scoreboard2 scoreboard[342]: During handling of the above exception, another exception occurred:
Aug 07 12:51:46 scoreboard2 scoreboard[342]: Traceback (most recent call last):
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/env/bin/scoreboard", line 11, in <module>
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     load_entry_point('dowski.scoreboard', 'console_scripts', 'scoreboard')()
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/scoreboard/scoreboard/scoreboard.py", line 46, in start
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     main(sys.argv)
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/scoreboard/scoreboard/scoreboard.py", line 66, in main
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     jobs.run()
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/usr/lib/python3.7/sched.py", line 151, in run
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     action(*argument, **kwargs)
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/scoreboard/scoreboard/tracker.py", line 52, in track
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     return self._track_internal(scheduled_game, post_game_callback, internal_tracking=False)
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/scoreboard/scoreboard/tracker.py", line 68, in _track_internal
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     raise e
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/scoreboard/scoreboard/tracker.py", line 65, in _track_internal
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     game_details = self.mlbapi.get_game_detail(scheduled_game.game_id)
Aug 07 12:51:46 scoreboard2 scoreboard[342]:   File "/home/pi/deploy/scoreboard/scoreboard/mlb.py", line 91, in get_game_detail
Aug 07 12:51:46 scoreboard2 scoreboard[342]:     raise FetchError(e)
Aug 07 12:51:46 scoreboard2 scoreboard[342]: scoreboard.errors.FetchError
```

**Comment by dowski** [comment]
Fixed in a536c97.
