### ISSUE TITLE
Score and inning display goes dark

### ISSUE THREAD

**Issue by dowski** [dowski/scoreboard#7]
There have been a few times this season where the home and away runs and the inning displays go dark. The balls, strikes and outs indicators will continue to show data.

This just happened after a game was postponed and I found the following traceback in the logs.

```
Sep 13 21:54:22 raspberrypi python[454]: Indians: -1, Twins: -1,  of -1 (b:0, s:0, o:0)
Sep 13 21:54:22 raspberrypi python[454]: game no longer trackable, status: Postponed
Sep 13 21:54:22 raspberrypi python[454]: Exception in thread Thread-1:
Sep 13 21:54:22 raspberrypi python[454]: Traceback (most recent call last):
Sep 13 21:54:22 raspberrypi python[454]: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
Sep 13 21:54:22 raspberrypi python[454]: self.run()
Sep 13 21:54:22 raspberrypi python[454]: File "/usr/lib/python2.7/threading.py", line 763, in run
Sep 13 21:54:22 raspberrypi python[454]: self.__target(*self.__args, **self.__kwargs)
Sep 13 21:54:22 raspberrypi python[454]: File "scoreboard/board/display.py", line 78, in _mainloop
Sep 13 21:54:22 raspberrypi python[454]: right_decimal_on=right_decimal)
Sep 13 21:54:22 raspberrypi python[454]: File "scoreboard/board/multiplexor.py", line 46, in set
Sep 13 21:54:22 raspberrypi python[454]: left_digit, right_digit = value
Sep 13 21:54:22 raspberrypi python[454]: ValueError: need more than 1 value to unpack
```

**Comment by dowski** [comment]
Haven't seen this for a long time, closing as obsolete.
