### ISSUE TITLE
Big board plugin should be more resilient to bad data

### ISSUE THREAD

**Issue by dowski** [dowski/scoreboard#9]
Here's an example from the logs where it crashed when the API returned 5 strikes.

```
Apr 10 18:16:25 scoreboard2 scoreboard[338]: Cleveland Indians: 0, Detroit Tigers: 0, Top of 1 (b:0, s:5, o:2, runners:())
Apr 10 18:16:25 scoreboard2 scoreboard[338]: Traceback (most recent call last):
Apr 10 18:16:25 scoreboard2 scoreboard[338]:   File "/home/pi/deploy/env/bin/scoreboard", line 11, in <module>
Apr 10 18:16:25 scoreboard2 scoreboard[338]:     load_entry_point('dowski.scoreboard', 'console_scripts', 'scoreboard')()
Apr 10 18:16:25 scoreboard2 scoreboard[338]:   File "/home/pi/deploy/scoreboard/scoreboard/scoreboard.py", line 47, in start
Apr 10 18:16:25 scoreboard2 scoreboard[338]:     main(sys.argv)
Apr 10 18:16:25 scoreboard2 scoreboard[338]:   File "/home/pi/deploy/scoreboard/scoreboard/scoreboard.py", line 67, in main
Apr 10 18:16:25 scoreboard2 scoreboard[338]:     jobs.run()
Apr 10 18:16:25 scoreboard2 scoreboard[338]:   File "/usr/lib/python3.7/sched.py", line 151, in run
Apr 10 18:16:25 scoreboard2 scoreboard[338]:     action(*argument, **kwargs)
Apr 10 18:16:25 scoreboard2 scoreboard[338]:   File "/home/pi/deploy/scoreboard/scoreboard/tracker.py", line 100, in track
Apr 10 18:16:25 scoreboard2 scoreboard[338]:     outs=render_state.outs)
Apr 10 18:16:25 scoreboard2 scoreboard[338]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/scoreboard.plugins.bigboard-0.9.0-py3.7.egg/bigboard/display.py", line 68, in set_inning_state
Apr 10 18:16:25 scoreboard2 scoreboard[338]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/scoreboard.plugins.bigboard-0.9.0-py3.7.egg/bigboard/display.py", line 90, in _refresh
Apr 10 18:16:25 scoreboard2 scoreboard[338]:   File "/home/pi/deploy/env/lib/python3.7/site-packages/scoreboard.plugins.bigboard-0.9.0-py3.7.egg/bigboard/display.py", line 125, in show_strikes
Apr 10 18:16:25 scoreboard2 scoreboard[338]: KeyError: 5
```

**Comment by dowski** [comment]
I haven't seen this be much of a problem in the last couple years. It should probably be more resilient, I just haven't had motivation to do it since it's "just worked".
